databases:
  - name: echofs-db
    databaseName: echofs
    user: echofs
    plan: free
    region: oregon

services:
  - type: web
    name: echofs-backend
    env: go
    region: oregon
    plan: free
    buildCommand: go mod tidy && go build -o server ./cmd/master/server/
    startCommand: ./server
    envVars:
      - key: PORT
        value: 10000
      - key: MASTER_PORT
        value: 10000
      - key: AWS_REGION
        value: us-east-1
      - key: LOG_LEVEL
        value: info
      - key: WORKER1_URL
        value: echofs-worker1.onrender.com:443
      - key: WORKER2_URL
        value: echofs-worker2.onrender.com:443
      - key: WORKER3_URL
        value: echofs-worker3.onrender.com:443
      - key: DATABASE_URL
        fromDatabase:
          name: echofs-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: DYNAMODB_FILES_TABLE
        sync: false
      - key: DYNAMODB_CHUNKS_TABLE
        sync: false
      - key: DYNAMODB_SESSIONS_TABLE
        sync: false